Proof of concept of syntax sugar
cirruslabs/cirrus-cli pull request #47
Opened 2020-08-25 21:32 UTC by fkorotkov

Essentially this is how we can create helper function for creating Cirrus CI tasks

2020-08-25 22:52 UTC, edigaryev requested changes

2020-08-25 22:52 UTC, edigaryev commented on pkg/larker/testdata/simple-task/expected.yaml
> +    - printenv
A newline is missing here (there are other occurrences too, marked with a red "no entry" icon).

2020-08-25 22:52 UTC, edigaryev commented on pkg/larker/larker.go
> +	// weird global init by Starlark
Perhaps a better idea would be to explain why do we enable floats here instead.

2020-08-25 22:52 UTC, edigaryev commented on pkg/larker/larker_test.go
> +// TestSugarCoatedTask ensures that .cirrus.star is able to use global functions for task generation.
```suggestion
// TestSugarCoatedTask ensures that .cirrus.star is able to use imported functions for task generation.
```

2020-08-26 08:30 UTC, edigaryev approved these changes

2020-08-26 10:15 UTC, fkorotkov commented
BTW I found an issue with the converter yesterday and finally found out the reason: `startlark.Int` is not just an `int`. Fixed in 2b79757cd130a5490b49229856f82b89df014993

2020-08-26 10:28 UTC, edigaryev approved these changes

2020-08-26 10:34 UTC, merged